/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTreeV2: typeof import('element-plus/es')['ElTreeV2']
    IfcViewing: typeof import('./src/components/IfcViewing/IfcViewing.vue')['default']
    IfcViewingBlock: typeof import('./src/components/IfcViewing/IfcViewingBlock.vue')['default']
    IfcViewingRequisites: typeof import('./src/components/IfcViewing/IfcViewingRequisites.vue')['default']
    IfcViewingRequisitesChild: typeof import('./src/components/IfcViewing/IfcViewingRequisitesChild.vue')['default']
    IfcViewingRequisitesOld: typeof import('./src/components/IfcViewing/IfcViewingRequisitesOld.vue')['default']
    IfcViewingTools: typeof import('./src/components/IfcViewing/IfcViewingTools.vue')['default']
    New_IfcViewingRequisites: typeof import('./src/components/IfcViewing/New_IfcViewingRequisites.vue')['default']
    Old_IfcViewingRequisites: typeof import('./src/components/IfcViewing/Old_IfcViewingRequisites.vue')['default']
    OLD_IfcViewingRequisites: typeof import('./src/components/IfcViewing/OLD_IfcViewingRequisites.vue')['default']
    Old_IfcViewingRequisitesChild: typeof import('./src/components/IfcViewing/Old_IfcViewingRequisitesChild.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
